/**
 * BCA STORE - Business Communication Knowledge Base
 * Training dataset for the AI Assistant.
 */

const BUSINESS_COMMUNICATION_KNOWLEDGE = {
  // Fundamentals of Business Communication
  "what is business communication": "Business communication is the exchange of information, ideas, and messages within and outside an organization for business purposes.",
  "importance of communication in business": "It helps in coordination, decision-making, teamwork, and maintaining good relationships with customers and employees.",
  "objectives of business communication": "Main objectives are sharing information, improving understanding, motivating employees, and achieving organizational goals.",
  "types of communication": "The main types are Verbal, Non-Verbal, Written, and Visual communication.",
  "formal communication": "Communication that follows official channels and organizational hierarchy.",
  "informal communication": "Casual communication that happens without official procedures, often called the 'grapevine'.",
  "verbal communication": "The exchange of information using spoken words.",
  "non-verbal communication": "Communication through gestures, facial expressions, posture, and body language.",
  "written communication": "Messages sent through letters, emails, reports, and notices.",
  "visual communication": "Using images, charts, graphs, and symbols to convey information.",
  "elements of communication": "The key elements are Sender, Message, Encoding, Channel, Receiver, Decoding, and Feedback.",
  "communication process": "It is the step-by-step process of sending and receiving messages effectively.",
  "encoding": "The process of converting thoughts into words, symbols, or gestures for transmission.",
  "decoding": "The process of interpreting and understanding a received message.",
  "feedback": "The receiver's response to the sender's message, indicating understanding or reaction.",
  "noise": "Any disturbance or interference that interrupts or distorts communication.",
  "barriers to communication": "Obstacles like noise, language differences, or emotional blocks that prevent effective communication.",
  "effective communication": "Communication that achieves its intended purpose clearly and accurately.",
  "7 cs of communication": "The 7 C's are Clarity, Conciseness, Correctness, Completeness, Concreteness, Courtesy, and Consideration.",
  "completeness": "Providing all necessary information so the receiver can take action.",
  "conciseness": "Giving information in as few words as possible without losing the core meaning.",
  "clarity": "Making sure the message is simple, specific, and easy to understand.",
  "correctness": "Using accurate facts, proper grammar, and appropriate language.",
  "concreteness": "Being specific, definite, and vivid rather than vague or general.",
  "courtesy": "Being polite, respectful, and positive in your communication.",
  "consideration": "Understanding the receiver's viewpoint and preparing the message from their perspective.",
  "downward communication": "Information flowing from a higher authority level to lower levels in an organization.",
  "upward communication": "Information flowing from employees or lower levels up to management.",
  "horizontal communication": "Communication between people at the same organizational level or department.",
  "diagonal communication": "Communication between people in different departments and at different levels.",
  "internal communication": "The exchange of information within an organization among its members.",
  "external communication": "Communication with people outside the organization, like customers or suppliers.",
  "business etiquette": "The code of professional manners and behavior expected in a workplace.",
  "professional communication": "Formal and respectful communication used in professional settings.",
  "active listening": "Paying full attention to the speaker, understanding the message, and responding appropriately.",
  "passive listening": "Hearing words without fully engaging or processing the meaning.",
  "empathy": "The ability to understand and share the feelings or viewpoints of others.",
  "emotional intelligence": "The capacity to recognize, understand, and manage your own and others' emotions.",
  "body language": "Communication through physical behavior, such as gestures and posture.",
  "eye contact": "A non-verbal cue that shows confidence, interest, and sincerity.",
  "posture": "The position in which someone holds their body, reflecting their attitude and confidence.",

  // Verbal & Non-Verbal Details
  "face-to-face communication": "Direct, in-person interaction that allows for immediate feedback and observation of non-verbal cues.",
  "telephonic etiquette": "Rules like speaking politely, introducing yourself, and listening carefully during a call.",
  "public speaking skills": "The ability to speak confidently and clearly before an audience.",
  "group discussion": "A structured discussion where multiple participants share and debate ideas on a topic.",
  "persuasive communication": "Communication designed to influence or change the opinions or actions of others.",
  "interpersonal communication": "The exchange of information and feelings between two or more people.",
  "mass communication": "Transmitting messages to a large audience through media like TV, radio, or the internet.",
  "kinesics": "The study of body movements, gestures, and facial expressions in communication.",
  "proxemics": "The study of how people use space and distance in communication.",
  "haptics": "Communication through the sense of touch.",
  "chronemics": "The study of the role of time in communication.",
  "paralanguage": "The non-verbal parts of speech, such as pitch, volume, and speed.",

  // Written Communication Details
  "business writing": "The style of writing used in professional settings, characterized by being purposeful and economical.",
  "proofreading": "The process of checking a document for errors in spelling, grammar, and punctuation.",
  "report writing": "Creating a formal document that presents information in an organized format for a specific audience.",
  "memo": "A short piece of writing used for internal communication within an organization.",
  "agenda": "A list of items to be discussed at a formal meeting.",
  "minutes": "The official written record of a meeting's discussions and decisions.",
  "business letter parts": "Standard parts include the Letterhead, Date, Inside Address, Salutation, Body, Closing, and Signature.",
  "inquiry letter": "A letter written to request information about a product, service, or policy.",
  "complaint letter": "A letter written to express dissatisfaction and request a solution.",
  "resume": "A brief document summarizing your education, work experience, and skills for job applications.",
  "cv": "Curriculum Vitae, a more detailed version of a resume used in academic or research fields.",
  "email etiquette": "Professional rules for digital communication, such as using a clear subject line and formal tone.",

  // Modern & Advanced
  "digital communication": "The exchange of information using electronic devices and digital platforms.",
  "video conferencing": "Conducting a meeting between people at different locations using video and audio.",
  "netiquette": "The set of professional and social rules followed in online communication.",
  "strategic communication": "Purposeful use of communication by an organization to fulfill its mission.",
  "crisis communication": "A sub-specialty of public relations designed to protect and defend an organization facing a public challenge to its reputation.",
  "conflict resolution": "The process of resolving a dispute or disagreement through communication and negotiation.",
  "negotiation skills": "The ability to discuss and reach an agreement that satisfies all parties involved.",
  "stakeholder communication": "Communicating with anyone who has an interest in or is affected by an organization's actions.",
  "public relations": "Managing the spread of information between an organization and the public.",
  
  // Group Discussion & Interview Skills
  "group discussion rules": "Listen carefully, speak clearly, respect others' opinions, don't interrupt, and stay focused on the topic.",
  "leadership in gd": "Showing leadership in a Group Discussion involves initiating the talk, summarizing points, and encouraging silent participants to speak.",
  "self-introduction in interview": "A brief summary of your name, educational background, key skills, and your interest in the specific role.",
  "strengths and weaknesses": "Common interview question; strengths should be job-related (e.g., fast learner), and weaknesses should be something you're actively improving (e.g., public speaking).",
  "interview etiquette": "Includes arriving on time, dressing professionally, maintaining eye contact, and sending a thank-you note after.",
  "salary negotiation": "The process of discussing and agreeing on your compensation and benefits with an employer.",
  
  // Presentation Skills
  "presentation objectives": "Presentations are usually intended to Inform, Persuade, Motivate, or Train an audience.",
  "presentation aids": "Tools like PowerPoint slides, charts, videos, and handouts used to support a presentation.",
  "elevator pitch": "A very brief (30-60 second) summary used to quickly and effectively define a person, product, or business.",
  "audience engagement": "Techniques like asking questions, using eye contact, and storytelling to keep the audience interested.",
  "q&a session": "The period at the end of a presentation where the speaker answers questions from the audience.",
  
  // Modern & Digital
  "social media communication": "Using platforms like LinkedIn or Twitter to build a professional brand and interact with customers.",
  "netiquette rules": "Be respectful, avoid 'shouting' in all caps, double-check your facts, and respect others' privacy online.",
  "remote communication": "Interacting with team members from different locations using tools like Zoom, Slack, or email.",
  "virtual teamwork": "Collaborating with a group of people who are not in the same physical office, relying on digital tools.",

  // 500 Basic Business Communication Terms (Batch 1)
  "sender": "The person who initiates and sends the message in the communication process.",
  "receiver": "The person who receives, decodes, and interprets the message.",
  "channel": "The medium (e.g., email, phone, face-to-face) used to transmit a message.",
  "oral communication": "Spoken communication used to exchange information orally.",
  "circular": "Information shared with a large number of people simultaneously.",
  "listening": "The active process of receiving and responding to spoken (and sometimes non-verbal) messages.",
  "gesture": "A movement of part of the body, especially a hand or the head, to express an idea or meaning.",
  "pitch": "The highness or lowness of a voice, which can change the meaning or emotion of a message.",
  "fluency": "The ability to speak or write a language easily, smoothly, and expressively.",
  "articulation": "The clear and distinct production of speech sounds.",
  "professionalism": "The competence or skill expected of a professional in the workplace.",
  "interview": "A formal meeting in which one or more persons question, consult, or evaluate another person.",
  "cover letter": "A letter sent with a resume to introduce yourself and summarize your interest in a job.",
  "application letter": "A formal request for a job, internship, or other professional opportunity.",
  "quotation letter": "A business letter providing the price and terms for specific goods or services.",
  "acknowledgement letter": "A letter confirming that something (like an order or a payment) has been received.",
  "appointment letter": "A formal letter confirming that a person has been selected for a job role.",
  "resignation letter": "A formal document notifying an employer that an employee is leaving their position.",
  "recommendation letter": "A letter written by someone who can vouch for your skills and character.",
  "subject line": "The short heading in an email that summarizes the main topic of the message.",
  "email signature": "Sender's contact details and professional title automatically added at the end of an email.",
  "cc": "Carbon Copy; used in emails to send a copy to someone for their information.",
  "bcc": "Blind Carbon Copy; used to send a copy to someone without other recipients knowing.",
  "webinar": "A seminar conducted over the internet.",
  "zoom meeting": "A virtual communication session held using the Zoom platform.",
  "teamwork": "The combined action of a group of people, especially when effective and efficient.",
  "leadership": "The action of leading a group of people or an organization.",
  "motivation": "The process that initiates, guides, and maintains goal-oriented behaviors in a team.",
  "persuasion": "The act of convincing someone to believe or do something.",
  "conflict": "A serious disagreement or argument, typically a protracted one.",
  "mediation": "Intervention in a dispute in order to resolve it, often by a neutral third party.",
  "coordination": "The organization of the different elements of a complex body or activity so as to enable them to work together effectively.",
  "collaboration": "The action of working with someone to produce or create something.",
  "strategy": "A plan of action or policy designed to achieve a major or overall aim.",
  "objective": "A specific result that a person or system aims to achieve.",
  "mission": "An organization's core purpose and focus that remains unchanged over time.",
  "vision": "A statement of what an organization would like to achieve in the long-term future.",
  "branding": "The process of creating a unique name and image for a product in the consumers' mind.",
  "marketing": "The action or business of promoting and selling products or services.",
  "customer service": "The assistance and advice provided by a company to those people who buy or use its products or services.",
  "slogan": "A short and striking or memorable phrase used in advertising.",
  "tagline": "A short, catchy phrase used to identify a brand or company.",
  "feedback loop": "A process in which the outputs of a system are circled back and used as inputs.",
  "clarity": "The quality of being easy to see, hear, or understand.",
  "conciseness": "The quality of being brief but comprehensive.",
  "completeness": "The state of having all the necessary parts or items.",
  "courtesy": "Polite behavior that shows respect for other people.",
  "concreteness": "The quality of being specific and definite rather than vague.",
  "consideration": "Careful thought, typically over a period of time, and understanding the audience's needs.",
  "grapevine": "The informal transmission of information, gossip, or rumors in an organization.",
  "vertical communication": "Communication that moves up or down the organizational hierarchy.",
  "report": "A detailed written account of a particular matter, often after investigation.",
  "proposal": "A plan or suggestion, especially a formal or written one, put forward for consideration.",
  "documentation": "The process of maintaining records or providing written evidence.",
  "drafting": "The preliminary stage of writing a document before the final version.",
  "editing": "The process of selecting and preparing written, visual, or audio material for publication.",
  "grammar": "The whole system and structure of a language.",
  "vocabulary": "The body of words used in a particular language or field.",
  "punctuation": "The marks used in writing to separate sentences and clarify meaning.",
  "introduction": "The opening section of a document or speech.",
  "conclusion": "The final section of a document or speech, summarizing key points.",
  "summary": "A brief statement or account of the main points of something.",
  "discussion": "The action or process of talking about something in order to reach a decision or to exchange ideas.",
  "debate": "A formal discussion on a particular topic in a public meeting or legislative assembly.",
  "seminar": "A conference or other meeting for discussion or training.",
  "workshop": "A meeting at which a group of people engage in intensive discussion and activity on a particular subject or project.",
  "conference": "A formal meeting for discussion, often spanning multiple days.",
  "briefing": "A meeting for giving information or instructions.",
  "announcement": "A formal public statement about a fact, occurrence, or intention.",
  "bulletin": "A short official statement or broadcast summary of news.",
  "press release": "An official statement issued to newspapers giving information on a particular matter.",
  "office order": "A formal instruction issued by a person in authority in an office.",
  "policy": "A course or principle of action adopted or proposed by a government, party, business, or individual.",
  "integrity": "The quality of being honest and having strong moral principles.",
  "accountability": "The fact or condition of being accountable; responsibility.",
  "responsibility": "The state or fact of having a duty to deal with something or of having control over someone.",
  "authority": "The power or right to give orders, make decisions, and enforce obedience.",
  "delegation": "The assignment of any authority to another person to carry out specific activities.",
  "management": "The process of dealing with or controlling things or people.",
  "supervisor": "A person who oversees and directs the work of others.",
  "employee": "A person employed for wages or salary.",
  "employer": "A person or organization that employs people.",
  "stakeholder": "A person with an interest or concern in something, especially a business.",
  "client": "A person or organization using the services of a lawyer or other professional person or company.",
  "consumer": "A person who purchases goods and services for personal use.",
  "supplier": "A person or organization that provides something, such as a product or service.",
  "vendor": "A person or company offering something for sale.",
  "partnership": "A business or firm owned and run by two or more partners.",
  "corporation": "A company or group of people authorized to act as a single entity.",
  "entrepreneurship": "The activity of setting up a business or businesses, taking on financial risks.",
  "innovation": "The action or process of innovating; a new method, idea, or product.",
  "productivity": "The effectiveness of productive effort, especially in industry.",
  "performance": "The action or process of carrying out or accomplishing an action, task, or function.",
  "appraisal": "An act of assessing something or someone, especially an employee's performance.",
  "training": "The action of teaching a person a particular skill or type of behavior.",
  "orientation": "A program to introduce new employees to their workplace and roles.",
  "recruitment": "The action of finding new people to join an organization.",
  "selection": "The process of picking the best candidate for a job role.",
  "placement": "The action of putting someone in a particular job or role.",
  "promotion": "The advancement of an employee to a higher rank or position.",
  "transfer": "The act of moving an employee to a different department or location.",
  "resignation": "The act of retiring or giving up a position.",
  "retirement": "The action or fact of leaving one's job and ceasing to work.",
  "salary": "A fixed regular payment, typically paid on a monthly basis.",
  "incentive": "A thing that motivates or encourages one to do something.",
  "bonus": "A sum of money added to a person's wages as a reward for good performance.",
  "target": "A goal to be reached or an objective to be achieved.",
  "deadline": "The latest time or date by which something should be completed.",
  "schedule": "A plan for carrying out a process or procedure, giving lists of intended events and times.",
  "time management": "The process of organizing and planning how to divide your time between specific activities.",
  "productivity tool": "Software or applications that help improve work efficiency.",
  "spreadsheet": "An electronic document in which data is arranged in the rows and columns of a grid.",
  "database": "A structured set of data held in a computer.",
  "analytics": "The systematic computational analysis of data or statistics.",
  "dashboard": "A visual interface that displays key information and metrics at a glance.",
  "infographic": "A visual image such as a chart or diagram used to represent information or data.",
  "chart": "A sheet of information in the form of a table, graph, or diagram.",
  "graph": "A diagram showing the relation between variable quantities.",
  "statistic": "A fact or piece of data from a study of a large quantity of numerical data.",
  "information": "Facts provided or learned about something or someone; processed data.",
  "knowledge": "Facts, information, and skills acquired by a person through experience or education.",
  "decision-making": "The action or process of making decisions, especially important ones.",
  "problem solving": "The process of finding solutions to difficult or complex issues.",
  "critical thinking": "The objective analysis and evaluation of an issue in order to form a judgment.",
  "creativity": "The use of the imagination or original ideas.",
  "swot analysis": "A study undertaken by an organization to identify its internal strengths and weaknesses, as well as its external opportunities and threats.",
  "risk": "A situation involving exposure to danger or loss.",
  "crisis communication": "Communication strategies used by an organization during a major emergency.",
  "reputation": "The beliefs or opinions that are generally held about someone or something.",
  "social media": "Websites and applications that enable users to create and share content.",
  "linkedin": "A professional networking site used for career and business connections.",
  "remote work": "A working style that allows professionals to work outside of a traditional office environment.",
  "hybrid work": "A flexible work model that supports a blend of in-office and remote work.",
  "virtual team": "A group of individuals who work together from different geographic locations.",
  "collaboration tool": "Software that helps people work together on a common task (e.g., Slack, Trello).",
  "cloud storage": "A model of computer data storage where digital data is stored in logical pools.",
  "cybersecurity": "The state of being protected against the criminal or unauthorized use of electronic data.",
  "password": "A secret word or phrase used to gain admission to something.",
  "authentication": "The process or action of proving or showing something to be true, genuine, or valid.",
  "encryption": "The process of converting information or data into a code.",
  "digital signature": "A mathematical technique used to validate the authenticity and integrity of a digital document.",
  "soft skills": "Personal attributes that enable someone to interact effectively and harmoniously with other people.",
  "hard skills": "Teachable abilities or skill sets that are easy to quantify.",
  "adaptability": "The quality of being able to adjust to new conditions.",
  "flexibility": "The quality of bending easily or being easily modified.",
  "reliability": "The quality of being trustworthy or performing consistently well.",
  "commitment": "The state or quality of being dedicated to a cause or activity.",
  "team spirit": "The desire to work together for a common goal.",
  "work culture": "The environment that you create for your employees.",
  "diversity": "The practice or quality of including or involving people from a range of different backgrounds.",
  "inclusion": "The action or state of including or being included within a group or structure.",
  "equality": "The state of being equal, especially in status, rights, and opportunities.",
  "broadcasting": "The distribution of audio or video content to a dispersed audience via any electronic mass communications medium.",
  "podcast": "A digital audio file made available on the internet for downloading to a computer or mobile device.",
  "newsletter": "A periodically published report containing news or information of interest to a group.",
  "campaign": "An organized course of action to promote a product or cause.",
  "networking": "The exchange of information and ideas among people with a common profession or special interest.",
  "business meeting": "A gathering of two or more people that has been convened for the purpose of achieving a common goal through verbal interaction.",
  "brainstorming": "A group creativity technique by which efforts are made to find a conclusion for a specific problem by gathering a list of ideas spontaneously contributed by its members.",
  "clarification": "The action of making a statement or situation less confused and more comprehensible.",
  "interpretation": "The action of explaining the meaning of something.",
  "technical writing": "Writing that provides information about complex technical subjects.",
  "annual report": "A comprehensive report on a company's activities throughout the preceding year.",
  "executive summary": "A short document or section of a document, produced for business purposes, that summarizes a longer report.",
  "feasibility report": "A document that assesses the potential for success of a proposed project.",
  "recommendation": "A suggestion or proposal as to the best course of action.",
  "notification": "The action of notifying someone or something.",
  "confirmation": "The action of confirming something or the state of being confirmed."
};

// Merge into the global knowledge base
if (typeof BCA_BOT_KNOWLEDGE !== 'undefined') {
  Object.assign(BCA_BOT_KNOWLEDGE, BUSINESS_COMMUNICATION_KNOWLEDGE);
}
