/**
 * BCA STORE - C Programming Knowledge Base
 * Training dataset for the AI Assistant.
 */

const C_PROGRAMMING_KNOWLEDGE = {
  // Basics of C Programming
  "what is c programming": "C is a general-purpose procedural programming language developed by Dennis Ritchie at Bell Labs.",
  "who developed c": "Dennis Ritchie developed the C language in the early 1970s.",
  "why is c a middle level language": "Because it combines the features of high-level languages (easy to read) with the efficiency of low-level languages (direct memory access).",
  "c file extension": "The source file extension is .c and the compiled executable extension is usually .exe (Windows) or .out (Linux).",
  "compiler vs interpreter": "A compiler translates the entire program into machine code before execution, while an interpreter translates and executes it line by line.",
  "main function in c": "main() is the starting point of execution for any C program. It is the first function called by the OS.",
  "c keywords": "ANSI C has 32 keywords (like int, if, else, for, while) which have predefined meanings and cannot be used as variable names.",
  "variable in c": "A variable is a named storage location in memory used to hold data values that can change during program execution.",
  "constant in c": "A constant is a fixed value that does not change during the program's execution, defined using 'const' or '#define'.",
  "c data types": "Basic types include int (integer), char (character), float (single-precision decimal), and double (double-precision decimal).",
  "sizeof operator": "sizeof() is a unary operator that returns the size (in bytes) of a data type or a variable.",
  "printf and scanf": "printf() is used to display output on the console, and scanf() is used to read input from the user.",
  "header file": "A file with .h extension containing declarations of functions and macros (e.g., stdio.h, conio.h).",
  "stdio.h": "Standard Input-Output header file, required for functions like printf() and scanf().",
  "token in c": "The smallest individual unit in a C program, such as keywords, identifiers, constants, and symbols.",
  "naming identifiers": "Must start with a letter or underscore, cannot contain spaces, and cannot be a keyword.",
  "comments in c": "Use // for single-line comments and /* ... */ for multi-line comments.",
  "semicolon in c": "A statement terminator that tells the compiler where one instruction ends.",
  "operators in c": "Symbols used for operations: Arithmetic (+, -, *, /), Relational (>, <, ==), and Logical (&&, ||, !).",
  "increment and decrement": "++ increases a variable's value by 1; -- decreases it by 1.",
  "type casting": "The process of converting one data type into another, either implicitly or explicitly.",
  "escape sequences": "Special character combinations starting with a backslash, like \\n for new line and \\t for horizontal tab.",
  "algorithm and flowchart": "An algorithm is a step-by-step logic description; a flowchart is its graphical representation.",
  "source code vs object code": "Source code is human-readable (.c); object code is the machine-readable version (.obj) produced after compilation.",
  "debugging": "The systematic process of finding and fixing errors (bugs) in a program.",

  // Decision Making and Loops
  "if else statement": "Used for conditional branching; executes one block if the condition is true and another if it is false.",
  "switch statement": "A multi-way decision-making statement that tests a variable against multiple 'cases'.",
  "break vs continue": "break exits the entire loop or switch block; continue skips the current iteration and moves to the next one.",
  "loop in c": "A construct that repeats a block of code as long as a condition is met (for, while, do-while).",
  "for loop": "A loop that includes initialization, condition, and increment/decrement in one line.",
  "while vs do-while": "while checks the condition first; do-while executes at least once and then checks the condition.",
  "infinite loop": "A loop that never terminates because its condition is always true.",
  "ternary operator": "The conditional operator (?:) which is a shorthand for if-else statements.",
  "logical operators": "Used to combine conditions: && (AND), || (OR), and ! (NOT).",

  // Arrays and Strings
  "array in c": "A collection of elements of the same data type stored in contiguous memory locations.",
  "string in c": "An array of characters that ends with a null character (\\0).",
  "null character": "The '\\0' character used to signal the end of a string in C memory.",
  "string.h functions": "Includes strlen() for length, strcpy() for copying, strcat() for joining, and strcmp() for comparison.",
  "ascii value": "The numeric representation of characters (e.g., 'A' is 65, 'a' is 97).",

  // Functions and Pointers
  "function in c": "A self-contained block of code that performs a specific task and can be called multiple times.",
  "recursion": "A programming technique where a function calls itself to solve a smaller sub-problem.",
  "pass by value vs reference": "Pass by value passes a copy; pass by reference passes the actual memory address using pointers.",
  "pointer in c": "A special variable that stores the memory address of another variable.",
  "null pointer": "A pointer that is assigned the value 0 or NULL, indicating it doesn't point to any valid address.",
  "dangling pointer": "A pointer pointing to a memory location that has already been freed or deleted.",
  "wild pointer": "A pointer that has been declared but not initialized, pointing to an arbitrary memory address.",

  // Memory & Advanced
  "dynamic memory allocation": "Allocating memory at runtime using functions like malloc(), calloc(), and realloc() from <stdlib.h>.",
  "memory leak": "Occurs when a program allocates dynamic memory but fails to free it before finishing.",
  "structure vs union": "A structure allocates separate memory for each member; a union shares the same memory space for all members.",
  "typedef": "Used to create an alias or new name for an existing data type.",
  "file handling in c": "Using functions like fopen(), fclose(), fprintf(), and fscanf() to read/write data to files.",
  "preprocessor directive": "Commands starting with # (like #include or #define) that are processed before actual compilation.",
  "macro": "A piece of code given a name, which is replaced by its value or logic during preprocessing.",
  "bitwise operators": "Operators that work on the binary bits of a number (&, |, ^, ~, <<, >>).",
  "command line arguments": "Parameters passed to the main() function when the program is run (argc and argv).",
  "volatile keyword": "Tells the compiler that a variable's value can change unexpectedly (e.g., by hardware).",

  // Specific C Programs & Logic
  "prime number in c": "A prime number is a number greater than 1 that has only two divisors: 1 and itself. Logic: Loop from 2 to n/2 and check if n % i == 0.",
  "fibonacci series in c": "A sequence where each number is the sum of the two preceding ones (0, 1, 1, 2, 3, 5...). Logic: next = t1 + t2; t1 = t2; t2 = next;",
  "factorial in c": "The product of all positive integers up to n (n!). Logic: fact = fact * i in a loop from 1 to n.",
  "palindrome number in c": "A number that remains the same when its digits are reversed. Logic: reverse the number and compare with the original.",
  "armstrong number in c": "A number that is equal to the sum of cubes of its digits (e.g., 153).",
  "searching algorithms": "Methods to find an element in an array, like Linear Search (checks one by one) and Binary Search (divides array in half).",
  "sorting algorithms": "Methods to arrange data in order, like Bubble Sort, Selection Sort, and Insertion Sort.",
  "matrix multiplication": "The process of multiplying two matrices; requires the number of columns in the first to equal the number of rows in the second.",
  "viva questions on c": "Common viva topics include Pointers, Recursion, Memory Allocation, and the difference between Structures and Unions.",

  // 250 C Programming Terms (Batch 1)
  "algorithm": "A step-by-step method for solving a problem or performing a task.",
  "compiler": "A program that translates C source code into machine-executable code.",
  "interpreter": "A program that executes instructions directly, line by line, without prior compilation.",
  "source code": "The human-readable version of a program written by a programmer.",
  "object code": "The product of a compiler, consisting of machine-level instructions.",
  "executable file": "A file containing a program in a format that the computer's OS can run directly.",
  "ide": "Integrated Development Environment; a software suite for coding, debugging, and compiling.",
  "turbo c": "A legacy integrated development environment and compiler for the C programming language.",
  "gcc": "GNU Compiler Collection; a popular open-source compiler for various programming languages.",
  "syntax": "The set of rules that defines the combinations of symbols that are considered to be a correctly structured program.",
  "keyword": "A reserved word in C that has a special meaning and cannot be used as an identifier.",
  "identifier": "A name given to a program element like a variable, function, or array.",
  "variable": "A storage location in memory that holds a value that can change.",
  "constant": "A value that cannot be altered by the program during its execution.",
  "data type": "A classification that specifies which type of value a variable has.",
  "int": "A basic data type used to store integer (whole) numbers.",
  "char": "A data type used to store a single character.",
  "float": "A data type used to store single-precision floating-point (decimal) numbers.",
  "double": "A data type used to store high-precision decimal numbers.",
  "void": "A keyword used to indicate that a function does not return a value or that a pointer is generic.",
  "main()": "The entry point where every C program starts its execution.",
  "header file": "A file containing function declarations and macro definitions to be shared between several source files.",
  "stdio.h": "Standard Input-Output header file for functions like printf and scanf.",
  "conio.h": "Console Input-Output header file, often used in older compilers for functions like clrscr and getch.",
  "math.h": "A header file containing declarations for mathematical functions like sqrt and pow.",
  "string.h": "A header file for performing operations on strings, such as length and concatenation.",
  "printf()": "A library function used to print formatted output to the console.",
  "scanf()": "A library function used to read formatted input from the standard input.",
  "getchar()": "Reads the next available character from the standard input.",
  "putchar()": "Writes a single character to the standard output.",
  "gets()": "An older function for reading a string from input (now considered unsafe; use fgets).",
  "puts()": "Writes a string and a trailing newline to the standard output.",
  "semicolon": "The character used to terminate a statement in C.",
  "comment": "Text in a program that is ignored by the compiler, used for explanation.",
  "single-line comment": "Starts with // and extends to the end of the line.",
  "multi-line comment": "Starts with /* and ends with */.",
  "operator": "A symbol that tells the compiler to perform specific mathematical or logical functions.",
  "arithmetic operator": "Symbols like +, -, *, /, and % used for basic math.",
  "relational operator": "Symbols like >, <, ==, and != used to compare two values.",
  "logical operator": "Symbols like &&, ||, and ! used for logical AND, OR, and NOT.",
  "assignment operator": "The = symbol used to assign a value to a variable.",
  "increment operator": "The ++ symbol which increases an integer value by one.",
  "decrement operator": "The -- symbol which decreases an integer value by one.",
  "unary operator": "An operator that takes only one operand (e.g., ++x, -x).",
  "binary operator": "An operator that takes two operands (e.g., x + y).",
  "modulus operator": "The % operator that returns the remainder of a division.",
  "bitwise operator": "An operator used to perform operations at the bit level of data.",
  "and operator": "The & bitwise operator or && logical operator.",
  "or operator": "The | bitwise operator or || logical operator.",
  "xor operator": "The ^ bitwise operator, returning true if only one operand is true.",
  "not operator": "The ~ bitwise operator or ! logical operator.",
  "left shift": "The << operator which shifts bits to the left, effectively multiplying by powers of 2.",
  "right shift": "The >> operator which shifts bits to the right, effectively dividing by powers of 2.",
  "expression": "A combination of variables, constants, and operators that is evaluated to a value.",
  "statement": "The smallest standalone element of a C program that expresses some action to be carried out.",
  "block": "A group of statements enclosed in curly braces {}.",
  "escape sequence": "A sequence of characters that does not represent itself when used inside a string, like \\n.",
  "\\n": "The newline escape sequence, used to move the cursor to the next line.",
  "\\t": "The horizontal tab escape sequence.",
  "\\0": "The null character, used to terminate strings in C.",
  "ascii": "American Standard Code for Information Interchange; a character encoding standard.",
  "unicode": "An international encoding standard for use with different languages and scripts.",
  "decision making": "Structures that allow a program to execute different code blocks based on conditions.",
  "if statement": "Executes a block of code if a specified condition is true.",
  "if-else": "Provides an alternative block of code if the if-condition is false.",
  "nested if": "An if statement that is placed inside another if or else block.",
  "switch": "A statement that allows a variable to be tested for equality against a list of values.",
  "case": "A specific value tested within a switch statement.",
  "default": "A keyword in a switch statement that executes if no case matches.",
  "loop": "A sequence of instructions that is continually repeated until a certain condition is reached.",
  "for loop": "A repetition control structure that allows you to efficiently write a loop that needs to execute a specific number of times.",
  "while loop": "A control flow statement that allows code to be executed repeatedly based on a given Boolean condition.",
  "do-while loop": "Similar to a while loop, except that it tests the condition at the end of the loop body.",
  "infinite loop": "A loop that never terminates because the condition is always true.",
  "nested loop": "A loop statement inside another loop statement.",
  "break": "Used to terminate a loop or switch statement immediately.",
  "continue": "Used to skip the current iteration of a loop and move to the next one.",
  "goto": "A jump statement that allows jumping to a labeled part of the same function.",
  "function": "A group of statements that together perform a task; the basic building block of a C program.",
  "function call": "An expression that passes control and arguments (if any) to a function.",
  "function definition": "The actual body of the function containing the code to be executed.",
  "function declaration": "Tells the compiler about a function's name, return type, and parameters.",
  "return type": "The data type of the value that a function returns to the caller.",
  "argument": "The actual value passed to a function when it is called.",
  "parameter": "A variable in a function definition that receives the value of an argument.",
  "recursion": "The process in which a function calls itself as a subroutine.",
  "base condition": "The condition that stops the recursive calls and prevents infinite recursion.",
  "call stack": "A stack data structure that stores information about the active subroutines of a computer program.",
  "library function": "A built-in function that is part of the C standard library.",
  "user-defined function": "A function that is created by the programmer to perform a specific task.",
  "scope": "The region of a program where a defined variable is accessible.",
  "local variable": "A variable declared inside a function or block, accessible only within that block.",
  "global variable": "A variable declared outside all functions, accessible from any part of the program.",
  "static variable": "A variable that retains its value even after its scope has ended.",
  "auto variable": "The default storage class for all local variables.",
  "extern variable": "Used to give a reference of a global variable that is visible to all the program files.",
  "register variable": "A variable stored in a CPU register instead of RAM for faster access.",
  "array": "A fixed-size sequenced collection of elements of the same data type.",
  "1d array": "A linear list of elements stored in contiguous memory.",
  "2d array": "An array of arrays, often used to represent matrices or tables.",
  "multidimensional array": "An array with more than two dimensions.",
  "array index": "The numeric position of an element in an array, starting from 0.",
  "string": "A sequence of characters terminated by a null character (\\0).",
  "strlen()": "Returns the number of characters in a string (excluding the null terminator).",
  "strcpy()": "Copies a source string into a destination string.",
  "strcat()": "Appends (concatenates) one string to the end of another.",
  "strcmp()": "Compares two strings and returns an integer based on their lexicographical order.",
  "pointer": "A variable that holds the memory address of another variable.",
  "address operator": "The & symbol used to get the memory address of a variable.",
  "dereference operator": "The * symbol used to access the value stored at a memory address.",
  "null pointer": "A pointer that does not point to any valid memory location.",
  "dangling pointer": "A pointer that points to a memory location that has been deallocated.",
  "wild pointer": "A pointer that has not been initialized and points to an arbitrary location.",
  "void pointer": "A generic pointer that can be used to point to any data type.",
  "pointer arithmetic": "The set of valid operations (like addition or subtraction) that can be performed on pointers.",
  "structure": "A user-defined data type that allows grouping variables of different types.",
  "union": "A user-defined data type that allows storing different data types in the same memory location.",
  "typedef": "A keyword used to define a new name for an existing data type.",
  "enum": "A user-defined data type consisting of a set of named integer constants.",
  "structure pointer": "A pointer variable that stores the address of a structure variable.",
  "dot operator": "The . symbol used to access members of a structure or union directly.",
  "arrow operator": "The -> symbol used to access structure or union members via a pointer.",
  "file handling": "The process of opening, reading, writing, and closing files in C.",
  "file pointer": "A pointer of type FILE* used to keep track of a file's state.",
  "fopen()": "Function used to open a file and return a file pointer.",
  "fclose()": "Function used to close an open file.",
  "fprintf()": "Writes formatted data to a file stream.",
  "fscanf()": "Reads formatted data from a file stream.",
  "fgetc()": "Reads a single character from a file.",
  "fputc()": "Writes a single character to a file.",
  "eof": "A constant representing the End Of File marker.",
  "buffer": "A temporary storage area in memory used during data transfer.",
  "dynamic memory allocation": "Memory allocated at runtime from the heap area.",
  "malloc()": "Allocates a single block of memory of a specified size.",
  "calloc()": "Allocates multiple blocks of memory and initializes them to zero.",
  "realloc()": "Changes the size of a previously allocated memory block.",
  "free()": "Deallocates dynamic memory that was previously allocated.",
  "heap memory": "The region of memory used for dynamic allocation.",
  "stack memory": "The region of memory used for function calls and local variables.",
  "memory leak": "A situation where a program fails to release memory it no longer needs.",
  "segmentation fault": "A specific kind of error caused by accessing memory that 'does not belong' to the program.",
  "preprocessor": "A tool that processes directives (like #include) before the code is compiled.",
  "#include": "Directive used to link header files to the program.",
  "#define": "Directive used to define macros or constants.",
  "macro": "A name given to a block of code that is substituted by the preprocessor.",
  "conditional compilation": "The process of compiling only certain parts of code based on conditions.",
  "command line argument": "Arguments passed to a program when it is executed from the terminal.",
  "argc": "Argument Count; an integer representing the number of command line arguments.",
  "argv": "Argument Vector; an array of strings representing the actual arguments.",
  "token": "The smallest unit of a program that has meaning to the compiler.",
  "lexical analysis": "The first phase of a compiler where characters are grouped into tokens.",
  "parsing": "The process of analyzing a string of tokens to determine its grammatical structure.",
  "syntax error": "An error that occurs when the code violates the grammatical rules of C.",
  "logical error": "An error that occurs when a program runs but produces incorrect results.",
  "runtime error": "An error that occurs while the program is running (e.g., division by zero).",
  "debugging": "The process of identifying and fixing errors in a program.",
  "debugger": "A software tool used to test and debug programs.",
  "flowchart": "A graphical representation of the sequence of operations in a program.",
  "pseudocode": "An informal high-level description of a computer program's logic.",
  "machine language": "The lowest-level programming language, consisting of binary digits.",
  "high-level language": "A programming language that is easy for humans to read and write.",
  "low-level language": "A language that provides little abstraction from a computer's instruction set.",
  "middle-level language": "A language like C that has features of both high and low levels.",
  "portability": "The ability of a program to run on different types of computer systems.",
  "modularity": "The degree to which a program's components may be separated and recombined.",
  "structured programming": "A programming paradigm aimed at improving clarity and quality by using subroutines and blocks.",
  "procedural programming": "A paradigm based on the concept of procedure calls.",
  "compilation": "The process of translating source code into object code.",
  "linker": "A program that combines object files into a single executable.",
  "loader": "A part of the OS that loads a program into memory and starts its execution.",
  "execution": "The process by which a computer performs the instructions of a program.",
  "binary number": "A number expressed in the base-2 numeral system.",
  "octal number": "A number expressed in the base-8 numeral system.",
  "hexadecimal": "A number expressed in the base-16 numeral system.",
  "boolean": "A data type with two possible values: true or false (represented as 1 and 0 in C).",
  "condition": "An expression that evaluates to true or false, used in control structures.",
  "iteration": "One complete execution of a loop's body.",
  "branching": "The process of choosing between two or more paths of execution.",
  "nested structure": "A structure defined as a member of another structure.",
  "nested switch": "A switch statement located inside another switch statement.",
  "nested function call": "A function called within the argument list of another function.",
  "prime number program": "A program that determines if a given number is prime.",
  "factorial program": "A program that calculates the factorial of a number using loops or recursion.",
  "fibonacci series": "A program that generates the sequence where each number is the sum of the two preceding ones.",
  "palindrome program": "A program that checks if a string or number reads the same forwards and backwards.",
  "pattern printing": "A program that uses nested loops to print geometric shapes or numbers.",
  "bubble sort": "A simple sorting algorithm that repeatedly steps through the list and swaps adjacent elements.",
  "selection sort": "An algorithm that repeatedly finds the minimum element and moves it to the sorted part.",
  "linear search": "A method for finding a target value within a list by checking each element sequentially.",
  "binary search": "A fast search algorithm that finds a target value by repeatedly dividing the search interval in half.",
  "matrix": "A rectangular array of numbers or elements arranged in rows and columns.",
  "transpose matrix": "A matrix formed by flipping a matrix over its diagonal, switching its row and column indices.",
  "determinant": "A scalar value that can be computed from the elements of a square matrix.",
  "algorithm complexity": "A measure of the amount of resources (time or space) required by an algorithm.",
  "time complexity": "A measure of the amount of time an algorithm takes to run as a function of the input size.",
  "space complexity": "A measure of the amount of memory an algorithm uses as a function of the input size.",
  "optimization": "The process of making code more efficient or higher-performing.",
  "dead code": "Portions of a program's source code that are never executed.",
  "embedded c": "A set of language extensions for the C programming language to support embedded systems.",
  "firmware": "Permanent software programmed into a read-only memory.",
  "kernel": "The core part of an operating system that manages hardware and system processes.",
  "process": "An instance of a computer program that is being executed.",
  "thread": "The smallest sequence of programmed instructions that can be managed independently by a scheduler.",
  "multitasking": "The concurrent execution of multiple tasks over a certain period of time.",
  "stdin": "Standard Input; the default stream for receiving data (usually the keyboard).",
  "stdout": "Standard Output; the default stream for displaying data (usually the monitor).",
  "stderr": "Standard Error; a separate stream used for error messages.",
  "formatting": "The process of arranging data in a specific visual layout.",
  "specifier": "A code used in printf/scanf to indicate the type of data being processed (e.g., %d).",
  "%d": "Format specifier used for signed decimal integers.",
  "%f": "Format specifier used for floating-point numbers.",
  "%c": "Format specifier used for single characters.",
  "%s": "Format specifier used for strings.",
  "%lf": "Format specifier used for double-precision floating-point numbers.",
  "type casting": "Explicitly converting a variable from one data type to another.",
  "implicit conversion": "Automatic type conversion performed by the compiler.",
  "explicit conversion": "Manual type conversion performed by the programmer using a cast operator.",
  "lvalue": "An expression that refers to a memory location (something that can be on the left of =).",
  "rvalue": "An expression that represents a value (something that is on the right of =).",
  "macro function": "A macro that takes arguments and behaves similarly to a function.",
  "inline function": "A function that is expanded at the point of call instead of being invoked via a traditional call mechanism.",
  "volatile keyword": "Informs the compiler that a variable's value may be changed by something outside the program.",
  "const keyword": "Used to declare a variable whose value remains constant and cannot be modified.",
  "sizeof()": "A compile-time operator that returns the size of a data type or object in bytes.",
  "ternary operator": "The ?: operator which provides a compact way to write if-else statements.",
  "comma operator": "An operator used to separate multiple expressions, evaluating them from left to right.",
  "associativity": "Determines the grouping of operators with the same precedence level.",
  "precedence": "Determines the order in which operators are evaluated in an expression.",
  "bit manipulation": "The act of algorithmically manipulating bits or other pieces of data shorter than a word.",
  "data structure": "A specialized format for organizing and storing data.",
  "linked list": "A linear data structure where each element is a separate object (node).",
  "stack": "A linear data structure that follows the Last-In-First-Out (LIFO) principle.",
  "queue": "A linear data structure that follows the First-In-First-Out (FIFO) principle.",
  "tree": "A hierarchical data structure consisting of nodes connected by edges.",
  "graph": "A collection of nodes (vertices) and the connections (edges) between them.",
  "hashing": "The process of converting an input into a fixed-size string of characters using a hash function.",
  "searching algorithm": "An algorithm used to retrieve information stored within some data structure.",
  "sorting algorithm": "An algorithm that puts elements of a list in a certain order.",
  "recursion tree": "A visual representation of the recursive calls made by a function.",
  "memory address": "A unique identifier used by a device for data tracking in the computer's memory.",
  "cpu": "The primary component of a computer that performs most of the processing inside the system.",
  "ram": "Random Access Memory; the hardware in a computing device where the OS and active data are kept.",
  "rom": "Read-Only Memory; a type of non-volatile memory used in computers.",
  "cache memory": "A small amount of very fast memory used to store frequently accessed data.",
  "bus": "A communication system that transfers data between components inside a computer.",
  "operating system": "System software that manages computer hardware and software resources.",
  "linux": "A family of open-source Unix-like operating systems based on the Linux kernel.",
  "windows": "A group of several proprietary graphical operating system families developed by Microsoft.",
  "portability": "The ability of code to be compiled and run on different hardware architectures with minimal changes.",
  "efficiency": "The ratio of useful work performed to the total energy or resources expended."
};

// Merge into the global knowledge base
if (typeof BCA_BOT_KNOWLEDGE !== 'undefined') {
  Object.assign(BCA_BOT_KNOWLEDGE, C_PROGRAMMING_KNOWLEDGE);
}
