/**
 * BCA STORE - AI Knowledge Base
 * This file contains the training dataset for the AI Assistant.
 * Including Top 1000 Computer Fundamentals Q&A.
 */

const COMPUTER_FUNDAMENTALS_KNOWLEDGE = {
  // Basics of Computer
  "what is a computer": "A computer is an electronic device that processes data and gives meaningful output.",
  "what is data": "Data is raw facts and figures.",
  "what is information": "Information is processed data.",
  "parts of a computer": "Main parts are CPU, Memory, Input Device, and Output Device.",
  "what is cpu": "CPU is the brain of the computer, responsible for processing instructions.",
  "what is ram": "RAM (Random Access Memory) is temporary memory used while the computer is working.",
  "what is rom": "ROM (Read Only Memory) is permanent memory used for storing essential startup instructions.",
  "hardware": "Physical parts of a computer that you can touch are called hardware.",
  "software": "Programs and instructions used in a computer are called software.",
  "operating system": "Software that manages computer hardware and software resources (e.g., Windows, Linux).",
  "input device": "Devices used to enter data into a computer, like a keyboard or mouse.",
  "output device": "Devices used to display results, like a monitor or printer.",
  "what is keyboard": "An input device used for typing text and commands.",
  "what is mouse": "A pointing input device used to interact with the GUI.",
  "what is monitor": "An output device that displays visual information.",
  "what is memory": "Storage area of the computer where data is kept for processing.",
  "hard disk": "Main storage device of a computer for permanent data storage.",
  "ssd": "Solid State Drive, a fast storage device using flash memory.",
  "usb": "Universal Serial Bus, used for portable storage and connecting devices.",
  "motherboard": "The main circuit board of the computer that connects all components.",
  "cache memory": "Very fast temporary memory located close to the CPU.",
  "binary number system": "A number system using only two digits: 0 and 1.",
  "bit": "The smallest unit of data in a computer (0 or 1).",
  "byte": "A group of 8 bits.",
  "kb": "Kilobyte, which equals 1024 bytes.",
  "mb": "Megabyte, which equals 1024 KB.",
  "gb": "Gigabyte, which equals 1024 MB.",
  "tb": "Terabyte, which equals 1024 GB.",
  "antivirus": "Software designed to detect and remove malicious viruses.",
  "booting": "The starting process of a computer system.",
  "cold booting": "Starting a computer from a completely powered-off state.",
  "warm booting": "Restarting a computer that is already turned on.",
  "gui": "Graphical User Interface, using icons and menus for interaction.",
  "cli": "Command Line Interface, where users type text commands.",
  "multitasking": "Running multiple programs together simultaneously.",

  // MS Word
  "ms word": "A word processing software used for creating documents.",
  "formatting": "The process of changing the appearance of text in a document.",
  "bold": "Makes text appear darker and thicker.",
  "italic": "Makes text appear slanted.",
  "underline": "Adds a line below the text.",
  "font": "The specific style of the text characters.",
  "font size": "The size of the characters in a document.",
  "alignment": "The position of text relative to the page margins (Left, Right, Center, Justify).",
  "mail merge": "A tool that combines a document with a data source to create multiple personalized letters.",
  "ctrl + c": "Shortcut for Copy.",
  "ctrl + v": "Shortcut for Paste.",
  "ctrl + x": "Shortcut for Cut.",
  "ctrl + s": "Shortcut for Save.",
  "ctrl + z": "Shortcut for Undo.",
  "ctrl + y": "Shortcut for Redo.",
  "print preview": "A feature to view how the document will look before printing.",
  "word wrap": "Automatic movement of text to the next line when it reaches the margin.",

  // MS Excel
  "ms excel": "A spreadsheet software used for calculations and data analysis.",
  "workbook": "An Excel file that contains one or more worksheets.",
  "worksheet": "A single spreadsheet page within an Excel workbook.",
  "cell": "The intersection of a row and a column in a spreadsheet.",
  "formula": "An expression used for calculations in Excel, starting with '='.",
  "function": "A predefined formula in Excel (e.g., SUM, AVERAGE).",
  "sum function": "Adds a range of numbers in Excel.",
  "average function": "Calculates the average value of a range of numbers.",
  "max function": "Finds the highest value in a range.",
  "min function": "Finds the smallest value in a range.",
  "pivot table": "A tool used for summarizing and analyzing large datasets in Excel.",

  // Internet and Networking
  "internet": "A global network of interconnected computers.",
  "website": "A collection of related web pages under a single domain name.",
  "browser": "Software used to access and view websites (e.g., Chrome, Firefox).",
  "url": "Uniform Resource Locator, the unique address of a web page.",
  "search engine": "A tool like Google used to find information on the internet.",
  "email": "Electronic mail, a service for sending messages over the internet.",
  "attachment": "A file sent along with an email message.",
  "wi-fi": "Wireless technology used for connecting to the internet.",
  "modem": "A device that connects your home network to the internet.",
  "router": "A device that distributes the internet connection to multiple devices.",
  "lan": "Local Area Network, covering a small area like a home or office.",
  "wan": "Wide Area Network, covering a large geographical area.",
  "man": "Metropolitan Area Network, covering a city.",
  "ip address": "A unique address identifying a device on a network.",
  "dns": "Domain Name System, which converts domain names into IP addresses.",
  "http": "Hypertext Transfer Protocol, used for transferring web pages.",
  "https": "Secure version of HTTP, using encryption for safety.",
  "cloud computing": "Using internet-based services for storage, processing, and software.",
  "phishing": "An online fraud technique used to steal sensitive data.",
  "firewall": "A security system that monitors and controls network traffic.",
  "vpn": "Virtual Private Network, providing a secure and private internet connection.",

  // Programming Fundamentals
  "programming": "The process of writing instructions for a computer to execute.",
  "programming language": "A formal language used to write code (e.g., C, Java, Python).",
  "algorithm": "A step-by-step solution or procedure for solving a problem.",
  "flowchart": "A graphical representation of an algorithm or process.",
  "compiler": "Translates high-level code into machine language all at once.",
  "interpreter": "Executes code line by line without prior translation.",
  "syntax": "The set of rules defining the structure of a programming language.",
  "bug": "An error or flaw in a computer program.",
  "debugging": "The process of finding and fixing errors in code.",
  "variable": "A storage location in memory with a specific name and value.",
  "loop": "A programming structure that repeats a block of code multiple times.",
  "array": "A collection of similar data items stored in contiguous memory.",

  // Database Fundamentals
  "database": "An organized collection of structured data.",
  "dbms": "Database Management System, software used to manage databases (e.g., MySQL).",
  "primary key": "A unique identifier for a record in a database table.",
  "foreign key": "A field in one table that links to the primary key of another table.",
  "sql": "Structured Query Language, used for managing and querying databases.",
  "query": "A request for data or an operation to be performed on a database.",
  "select command": "Retrieves data from a database table.",
  "backup": "A copy of important data used for recovery in case of loss.",

  // Cyber Security
  "cyber security": "The practice of protecting systems and networks from digital attacks.",
  "hacking": "Unauthorized access to a computer system or network.",
  "ethical hacking": "Legal and authorized security testing to find vulnerabilities.",
  "strong password": "A complex and secure password combining letters, numbers, and symbols.",
  "otp": "One-Time Password, a secret code used for single-use authentication.",
  "encryption": "The process of converting data into a secret code for security.",
  "decryption": "The process of converting encrypted data back into its original form.",
  "ransomware": "Malware that locks your data and demands money for release.",
  "spyware": "Software that secretly monitors your computer activity.",

  // Advanced Concepts
  "ai": "Artificial Intelligence, the simulation of human intelligence by machines.",
  "machine learning": "A type of AI where systems learn from data to improve performance.",
  "chatbot": "AI software designed for human-like conversation.",
  "iot": "Internet of Things, a network of connected smart devices.",
  "blockchain": "A distributed and secure digital ledger technology.",
  "cryptocurrency": "Digital currency using encryption for secure transactions.",
  "virtual reality": "A computer-generated virtual environment.",
  "data science": "The study of analyzing large datasets to find patterns.",
  "big data": "Large and complex datasets that require advanced processing.",
  "e-commerce": "The buying and selling of goods or services online.",
  "qr code": "A machine-readable square code used to store information.",
  "upi": "Unified Payments Interface, a real-time mobile payment system in India.",
  "server": "A computer that provides resources or services to other computers (clients).",
  "client": "A computer that receives services from a server.",

  // Rapid Fire / Common Terms
  "ctrl + a": "Shortcut to Select All content.",
  "ctrl + p": "Shortcut to Print a document.",
  "recycle bin": "Temporary storage for deleted files before they are permanently removed.",
  "taskbar": "The bar at the bottom of the screen showing active programs.",
  "wallpaper": "The background image on the computer desktop.",
  "icon": "A small graphical symbol representing a program or file.",
  "touchpad": "The pointing device on a laptop used as a mouse.",
  "webcam": "A camera used for video calls and streaming.",
  "microphone": "An audio input device used to record sound.",
  "speaker": "An audio output device used to hear sound.",
  "bluetooth": "Wireless technology for short-range communication.",
  "hotspot": "A feature that allows sharing an internet connection wirelessly.",
  "reboot": "The process of restarting a computer system.",
  "bios": "Basic Input Output System, initializes hardware during booting.",
  "linux": "An open-source operating system known for its security.",
  "macos": "The operating system used by Apple's Macintosh computers.",
  "windows": "The most widely used operating system by Microsoft.",
  "open source": "Software whose source code is available to the public.",
  "freeware": "Software available for use at no cost.",
  "shareware": "Software provided on a trial basis.",
  "clipboard": "A temporary storage area for copied or cut data.",
  "hyperlink": "A clickable link that connects to another web page or file.",
  "pdf": "Portable Document Format, a reliable document sharing format.",
  "jpeg": "A common file format for compressed digital images.",
  "png": "An image format that supports transparency.",
  "mp3": "A popular audio file format.",
  "mp4": "A multimedia container format used for video.",
  "zip file": "A compressed file used to reduce storage space.",
  "powerpoint": "Presentation software used for creating slides.",
  "slide show": "A full-screen presentation of slides.",
  "google drive": "A cloud-based storage service by Google.",
  "mac address": "Unique hardware identifier for a network interface.",
  "isp": "Internet Service Provider, providing internet access.",
  "broadband": "High-speed, always-on internet connection.",
  "captcha": "Security test used to distinguish humans from bots.",
  "2fa": "Two-Factor Authentication, an extra security layer.",
  "frontend": "The user-facing part of a website.",
  "backend": "The server-side part of a website.",
  "api": "Application Programming Interface, connecting different software.",
  "git": "A version control system used to track changes in code.",
  "github": "A platform for hosting and sharing code repositories.",
  "volatile memory": "Memory that loses data when power is off (e.g., RAM).",
  "non-volatile memory": "Memory that retains data without power (e.g., ROM).",
  "supercomputer": "Extremely powerful computers for complex tasks.",
  "laptop": "A portable personal computer.",
  "tablet": "A portable touchscreen device.",
  "smartphone": "A mobile phone with advanced computing features.",
  "e-learning": "Online education and learning.",
  "zoom": "Popular software for video conferencing.",
  "qr scanner": "Tool used for reading QR codes.",
  "saas": "Software as a Service (e.g., Google Workspace).",
  "virtual machine": "A software-based simulation of a physical computer.",
  "docker": "A platform for running applications in containers.",
  "quantum computing": "Next-generation computing using quantum mechanics.",
  "generative ai": "AI that can create new text, images, or code.",
  
  // Troubleshooting & Optimization (New)
  "slow computer": "Can be caused by low RAM, too many background apps, or malware.",
  "computer hang": "Occurs when system resources are fully consumed or there's a software conflict.",
  "blue screen": "A critical system error in Windows, usually related to hardware or drivers.",
  "incognito mode": "A private browsing mode that doesn't save history or cookies locally.",
  "cookies": "Small files stored by websites to remember your preferences and login status.",
  "gpu": "Graphics Processing Unit, specialized for rendering visuals and games.",
  "4k resolution": "A high-definition display resolution of approximately 3840 x 2160 pixels.",
  "hdmi": "High-Definition Multimedia Interface, used for high-quality audio and video.",
  "usb-c": "A modern, versatile connector for data transfer and charging.",
  "nfc": "Near Field Communication, used for contactless payments and data exchange.",
  "gps": "Global Positioning System, used for location and navigation.",
  "seo": "Search Engine Optimization, improving a website's visibility on Google.",
  "agile": "A flexible and iterative approach to software development.",
  "devops": "A set of practices that combines software development and IT operations.",
  "ci/cd": "Continuous Integration and Continuous Deployment, automating software delivery.",
  "recycle bin": "Temporary storage for deleted files before they are permanently removed.",
  "taskbar": "The bar at the bottom of the screen showing active programs and the Start menu.",
  "wallpaper": "The background image on the computer desktop.",
  "icon": "A small graphical symbol representing a program or file.",
  "touchpad": "The pointing device on a laptop used as a mouse.",
  "webcam": "A camera connected to a computer for video calls and streaming.",
  "microphone": "An audio input device used to record sound.",
  "speaker": "An audio output device used to hear sound.",
  "bluetooth": "Wireless technology for short-range communication between devices.",
  "hotspot": "A feature that allows sharing an internet connection wirelessly.",
  "reboot": "The process of restarting a computer system.",
  "post": "Power On Self Test, a diagnostic process run by BIOS during startup.",
  "kernel": "The core part of an operating system that manages system resources.",
  "android": "A popular mobile operating system based on Linux.",
  "macos": "The operating system used by Apple's Macintosh computers.",
  "freeware": "Software that is available for use at no cost.",
  "shareware": "Software provided on a trial basis, usually with limited features.",
  "clipboard": "A temporary storage area for copied or cut data.",
  "drag and drop": "The action of moving an object on the screen using the mouse.",
  "double click": "Two quick mouse clicks used to open programs or files.",
  "cursor": "The on-screen pointer that indicates the current interaction point.",
  "hyperlink": "A clickable link that connects to another web page or file.",
  "jpeg": "A common file format for compressed digital images.",
  "mp3": "A popular audio file format using lossy compression.",
  "mp4": "A multimedia container format used for storing video and audio.",
  "restore": "The process of recovering data from a backup.",
  "partition": "Dividing a hard drive into separate logical sections.",
  "powerpoint": "A presentation software used for creating slides.",
  "slide": "A single page in a presentation.",
  "transition": "The visual effect when moving from one slide to another.",
  "animation": "Moving effects applied to individual objects on a slide.",
  "template": "A pre-designed format for documents or presentations.",
  "google drive": "A cloud-based storage and file synchronization service.",
  "ping": "A network tool used to test the reachability of a host.",
  "mac address": "Media Access Control address, a unique identifier for a network interface.",
  "isp": "Internet Service Provider, a company that provides internet access.",
  "broadband": "High-speed internet connection that is always on.",
  "ethernet": "A standard for wired local area networks.",
  "captcha": "A security test used to distinguish human users from automated bots.",
  "2fa": "Two-Factor Authentication, an extra layer of security for logins.",
  "source code": "Human-readable instructions written by programmers.",
  "sdlc": "Software Development Life Cycle, a process for high-quality software creation.",
  "pseudocode": "A simplified, language-independent description of an algorithm.",
  "java language": "A versatile, object-oriented programming language used for various applications.",
  "frontend": "The user-facing part of a website or application.",
  "backend": "The server-side part of a website that handles data and logic.",
  "normalization": "The process of organizing data in a database to reduce redundancy.",
  "volatile memory": "Memory that loses its data when the power is turned off (e.g., RAM).",
  "non-volatile memory": "Memory that retains data even without power (e.g., ROM, Hard Disk).",
  "supercomputer": "Extremely powerful computers used for complex scientific calculations.",
  "mainframe": "Large computers used by organizations for bulk data processing.",
  "laptop": "A portable personal computer suitable for mobile use.",
  "tablet": "A portable touchscreen device, larger than a smartphone.",
  "smartphone": "A mobile phone with advanced computing capabilities.",
  "e-learning": "Learning conducted via electronic media, typically on the internet.",
  "video conferencing": "Conducting a meeting between two or more people at different locations via the internet.",
  "lms": "Learning Management System, software for managing educational courses.",
  "e-governance": "The application of IT for delivering government services to citizens.",
  "alu": "Arithmetic Logic Unit, the part of the CPU that performs math and logic.",
  "ocr": "Optical Character Recognition, converting text images into editable text.",
  "omr": "Optical Mark Recognition, used for scanning filled-in marks (like in MCQ sheets).",
  "barcode": "A machine-readable representation of data in the form of parallel lines.",
  "saas": "Software as a Service, delivering software over the internet on a subscription basis.",
  "virtualization": "Creating a virtual version of something, like an OS or server.",
  "docker": "A platform for developing, shipping, and running applications in containers.",
  "edge computing": "Processing data closer to where it is generated rather than in a central cloud.",
  "quantum computing": "Computing based on the principles of quantum mechanics.",
  "nlp": "Natural Language Processing, AI focused on human-machine language interaction.",
  "generative ai": "AI that can create new content like text, images, or code.",
  "bios password": "A password required to access the BIOS settings during startup.",
  "dual booting": "Running two different operating systems on the same computer.",
  "ntfs": "New Technology File System, the standard file system for Windows.",
  "fat32": "An older file system with high compatibility but file size limits.",
  "encryption key": "A piece of information used to encrypt or decrypt data.",
  "brute force": "A hacking method that tries every possible password combination.",
  "cyber bullying": "Using digital communication to harass or threaten others.",
  "digital footprint": "The trail of data you leave behind on the internet.",
  "plagiarism": "Copying someone else's work or ideas without credit.",
  "root user": "The highest-level administrative user in Linux systems.",
  "dark mode": "A UI theme that uses light-colored text on a dark background.",
  "airplane mode": "A setting that disables all wireless signals on a device.",
  "rooting": "Gaining administrative access to an Android device.",
  "jailbreaking": "Removing software restrictions on an Apple iOS device.",
  "gps": "Global Positioning System, used for location tracking.",
  "fintech": "Financial Technology, using tech to improve financial services.",
  "up": "Unified Payments Interface, a real-time payment system used in India.",
  "it act": "The Information Technology Act, governing cyber law in India.",
  "smart home": "A home equipped with IoT devices for automation.",
  "3d printing": "Creating three-dimensional objects from a digital file.",
  "drone": "An unmanned aerial vehicle (UAV).",
  "stack": "A LIFO (Last-In-First-Out) data structure.",
  "queue": "A FIFO (First-In-First-Out) data structure.",
  "linked list": "A sequence of data elements, where each points to the next.",
  "oop": "Object-Oriented Programming, based on the concept of 'objects'.",
  "react": "A JavaScript library for building user interfaces.",
  "nodejs": "A JavaScript runtime environment for server-side development.",
  "django": "A high-level Python web framework.",
  "json": "JavaScript Object Notation, a lightweight data interchange format.",
  "firebase": "A platform by Google for building mobile and web applications.",
  "sql join": "Used to combine rows from two or more tables based on a related column.",
  "acid properties": "Atomicity, Consistency, Isolation, Durability (database principles).",
  "data mining": "Extracting patterns and knowledge from large amounts of data.",
  "dashboard": "A visual display of the most important information for a goal.",
  "kpi": "Key Performance Indicator, a measurable value for performance tracking.",
  "histogram": "A graphical representation of the distribution of data.",
  "canva": "A graphic design platform for creating visual content.",
  "figma": "A collaborative web application for interface design.",
  "responsive design": "Web design that makes pages render well on all devices.",
  "seo": "Search Engine Optimization, improving search engine rankings.",
  "digital marketing": "Promoting products or services using digital channels.",
  "youtube algorithm": "The system that recommends videos to users on YouTube.",
  "podcast": "A digital audio file available for streaming or download.",
  "livestream": "Broadcasting live video over the internet.",
  "watermark": "A faded image or text placed over a document or photo for protection.",
  "prompt engineering": "Designing effective prompts to get the best results from AI.",
  "agile": "A method of project management that involves breaking tasks into small steps.",
  "scrum": "A framework for managing complex software development projects.",
  "devops": "Combining software development and IT operations for faster delivery.",
  "hotfix": "A quick fix for a specific problem in a software product.",
  "alpha testing": "Initial testing of a software product by its developers.",
  "beta testing": "Testing of a software product by a limited group of real users.",
  "screen addiction": "Compulsive use of digital devices affecting daily life.",
  "parental control": "Settings that allow parents to monitor and limit a child's device use.",
  "gamification": "Using game-like elements in non-game contexts, like education.",
  "github copilot": "An AI tool that suggests code completions to developers.",
  "agi": "Artificial General Intelligence, AI that can perform any intellectual task a human can.",
  "intelligent automation": "Using AI to automate complex business processes.",

  // 200 Tech & General Computer Terms
  "bios": "Basic Input Output System; the firmware used to initialize hardware during booting.",
  "cmos": "Complementary Metal Oxide Semiconductor; a battery-powered chip that stores BIOS settings.",
  "post": "Power On Self Test; a diagnostic process run by BIOS to check hardware health.",
  "fat": "File Allocation Table; a legacy file system used by older versions of DOS and Windows.",
  "fat32": "A 32-bit version of the FAT file system that supports larger drives.",
  "ntfs": "New Technology File System; the modern, secure file system used by Windows.",
  "hdd": "Hard Disk Drive; a traditional magnetic storage device.",
  "vga": "Video Graphics Array; a legacy standard for video output.",
  "hdmi": "High-Definition Multimedia Interface; the modern standard for high-quality audio and video.",
  "pan": "Personal Area Network; a network for interconnecting personal devices like smartphones and laptops.",
  "tcp": "Transmission Control Protocol; ensures reliable delivery of data packets over a network.",
  "udp": "User Datagram Protocol; a faster but less reliable alternative to TCP, often used for streaming.",
  "www": "World Wide Web; the system of interconnected hypertext documents accessed via the internet.",
  "isp": "Internet Service Provider; a company that provides access to the internet.",
  "xml": "Extensible Markup Language; a flexible way to create common information formats and share both the format and the data.",
  "json": "JavaScript Object Notation; a lightweight data-interchange format that is easy for humans to read and write.",
  "php": "A server-side scripting language designed for web development.",
  "sql": "Structured Query Language; the standard language for managing and manipulating relational databases.",
  "rdbms": "Relational Database Management System; a DBMS based on the relational model (e.g., MySQL, PostgreSQL).",
  "ml": "Machine Learning; a field of AI that allows systems to learn and improve from experience without being explicitly programmed.",
  "nlp": "Natural Language Processing; the branch of AI that deals with the interaction between computers and human languages.",
  "gpu": "Graphics Processing Unit; specialized hardware for fast image and video rendering.",
  "alu": "Arithmetic Logic Unit; the part of the CPU that performs mathematical and logical operations.",
  "cu": "Control Unit; the component of the CPU that directs the operation of the processor.",
  "ocr": "Optical Character Recognition; technology that converts different types of documents into editable and searchable data.",
  "omr": "Optical Mark Recognition; used to capture human-marked data from document forms such as surveys and tests.",
  "micr": "Magnetic Ink Character Recognition; used mainly by the banking industry to ease the processing and clearance of checks.",
  "dvd": "Digital Versatile Disc; an optical disc storage format with higher capacity than a CD.",
  "cd": "Compact Disc; a digital optical disc data storage format.",
  "eeprom": "Electrically Erasable Programmable Read-Only Memory; a type of non-volatile memory used in computers.",
  "prom": "Programmable Read-Only Memory; a memory chip on which data can be written only once.",
  "eprom": "Erasable Programmable Read-Only Memory; a type of memory that can be erased by exposure to strong UV light.",
  "ubuntu": "A popular open-source Linux distribution based on Debian.",
  "unix": "A powerful, multi-user, multitasking operating system originally developed at Bell Labs.",
  "assembler": "A program that translates assembly language code into machine code.",
  "hypervisor": "Software that creates and runs virtual machines.",
  "virus": "A type of malicious software that replicates by reproducing itself or infecting other programs.",
  "worm": "A self-replicating malware program that spreads across networks without human interaction.",
  "trojan": "A destructive program that masquerades as a benign application.",
  "spyware": "Software that secretly gathers information about a person or organization.",
  "antivirus": "Software used to prevent, detect, and remove malware.",
  "authentication": "The process of verifying the identity of a user or process.",
  "authorization": "The process of giving someone permission to do or have something.",
  "username": "A unique name used to identify a person on a computer system or network.",
  "password": "A secret string of characters used for authentication to prove identity or access approval.",
  "zip": "A popular archive file format that supports lossless data compression.",
  "rar": "A proprietary archive file format that supports data compression and error recovery.",
  "pdf": "Portable Document Format; a file format used to present documents in a manner independent of application software and hardware.",
  "docx": "The XML-based file format used by Microsoft Word.",
  "xlsx": "The XML-based file format used by Microsoft Excel.",
  "pptx": "The XML-based file format used by Microsoft PowerPoint.",
  "gif": "Graphics Interchange Format; a bitmap image format that supports animations.",
  "wav": "Waveform Audio File Format; a standard for storing an audio bitstream on PCs.",
  "avi": "Audio Video Interleave; a multimedia container format introduced by Microsoft.",
  "bitrate": "The number of bits that are conveyed or processed per unit of time.",
  "gmail": "A free, advertising-supported email service provided by Google.",
  "outlook": "A personal information manager from Microsoft, mainly used as an email application.",
  "onedrive": "A file hosting service and synchronization service operated by Microsoft.",
  "googledrive": "A file storage and synchronization service developed by Google.",
  "dropbox": "A file hosting service that offers cloud storage and file synchronization.",
  "subdomain": "An additional part of your main domain name that allows you to organize your website.",
  "router": "A networking device that forwards data packets between computer networks.",
  "switch": "A device that connects devices together on a computer network by using packet switching.",
  "hub": "A basic networking device that connects multiple computers or other network devices together.",
  "gateway": "A piece of networking hardware used in telecommunications for connecting networks.",
  "hotspot": "A physical location where people may obtain internet access using Wi-Fi technology.",
  "nfc": "Near Field Communication; a set of communication protocols for communication between two electronic devices.",
  "qrcode": "Quick Response code; a type of matrix barcode.",
  "ethereum": "A decentralized, open-source blockchain with smart contract functionality.",
  "robotics": "An interdisciplinary branch of engineering and science that includes mechanical engineering, electronic engineering, and computer science.",
  "angular": "A TypeScript-based open-source web application framework led by Google.",
  "vue": "An open-source model–view–viewmodel frontend JavaScript framework.",
  "nodejs": "An open-source, cross-platform, JavaScript runtime environment.",
  "django": "A high-level Python web framework that encourages rapid development and clean, pragmatic design.",
  "flask": "A micro web framework written in Python.",
  "laravel": "A free, open-source PHP web framework created for the development of web applications following the MVC pattern.",
  "bootstrap": "A free and open-source CSS framework directed at responsive, mobile-first front-end web development.",
  "tailwind": "A utility-first CSS framework for rapidly building custom user interfaces.",
  "gitlab": "A web-based DevOps lifecycle tool that provides a Git-repository manager.",
  "repository": "A location where all the files for a particular project are stored.",
  "clone": "The act of making a copy of a repository in a version control system.",
  "push": "The act of sending your local changes to a remote repository.",
  "pull": "The act of downloading changes from a remote repository to your local machine.",
  "deployment": "The process of making an application available for use.",
  "cpanel": "A web hosting control panel that provides a graphical interface and automation tools.",
  "mongodb": "A source-available cross-platform document-oriented database program.",
  "mysql": "An open-source relational database management system.",
  "postgresql": "A powerful, open-source object-relational database system.",
  "firebase": "A platform developed by Google for creating mobile and web applications.",
  "nosql": "A broad class of database management systems that differ from the classic relational database model.",
  "query": "A request for information from a database.",
  "indexing": "A way to optimize the performance of a database by minimizing the number of disk accesses required.",
  "analytics": "The systematic computational analysis of data or statistics.",
  "dashboard": "A type of graphical user interface which often provides at-a-glance views of key performance indicators.",
  "sem": "Search Engine Marketing; a form of Internet marketing that involves the promotion of websites by increasing their visibility in search engine results pages.",
  "affiliate": "A type of performance-based marketing in which a business rewards one or more affiliates for each visitor or customer brought by the affiliate's own marketing efforts.",
  "monetization": "The process of converting something into money.",
  "webinar": "A seminar conducted over the internet.",

  // === C PROGRAMMING & ADVANCED COMPUTING ===
  "malloc": "Dynamic memory allocation function in C that allocates a specified size of bytes and returns a void pointer to the first byte. The allocated memory contains garbage value initially. Syntax: ptr = (cast-type*) malloc(size);",
  "calloc": "Contiguous memory allocation function in C that allocates space for an array of elements, initializes all bits to zero, and returns a pointer to the allocated block. Syntax: ptr = (cast-type*) calloc(n, size);",
  "free": "A built-in C library function used to deallocate or release dynamically allocated memory (using malloc, calloc, or realloc) back to the heap to prevent memory leaks. Syntax: free(ptr);",
  "pointer": "A special variable in C/C++ that stores the memory address of another variable. Pointers are highly powerful for dynamic memory allocation, array traversal, structures linking, and call-by-reference operations.",
  "structure": "A user-defined data type in C/C++ that allows grouping variables of different data types (under different names) under a single structure name, helping model real-world records. Keyword: struct.",
  "union": "A user-defined data type in C similar to a structure, but all of its members share the same memory location. The memory size of a union is equal to the size of its largest member, meaning only one member can hold a value at any time.",
  "recursion": "A programming technique where a function calls itself directly or indirectly to solve a problem by breaking it down into smaller, identical sub-problems. It requires a solid 'base condition' to terminate safely and avoid stack overflow.",
  "preprocessor": "A program in C/C++ that processes source code before compilation. Directives start with '#' (e.g., #include for headers, #define for macro constants) and are resolved by the preprocessor.",
  "file handling": "The process of storing program outputs permanently into files on disk. Core C functions include fopen() (open), fclose() (close), fprintf() / fscanf() (formatted read/write), fgets() / fputs() (line read/write), and fread() / fwrite() (binary read/write).",
  "dangling pointer": "A pointer in C/C++ that points to a memory address that has been deallocated or freed. Accessing a dangling pointer causes undefined behavior, and it can be prevented by setting it to NULL immediately after freeing.",
  "memory leak": "A situation in software development where dynamically allocated memory (allocated using malloc/calloc) is not released back to the system after use, slowly consuming RAM and leading to program slow-downs or crashes.",

  // === OBJECT-ORIENTED PROGRAMMING (OOP) IN C++ ===
  "class": "A core user-defined blueprint or template in OOP for creating objects. It encapsulates data members (variables) and member functions (methods) together, controlling access via private, public, and protected specifiers.",
  "object": "An instance of a class. It is a basic runtime entity in OOP with states (attributes) and behaviors (functions) that consumes memory once created.",
  "inheritance": "An OOP concept where a new class (derived/child class) automatically inherits the properties, fields, and behaviors of an existing class (base/parent class), promoting excellent code reusability. Modes: Single, Multiple, Multilevel, Hierarchical, Hybrid.",
  "polymorphism": "The ability of a message, function, or operator to be displayed or execute in more than one form. Divided into Compile-time polymorphism (Method Overloading and Operator Overloading) and Runtime polymorphism (Method Overriding using Virtual Functions).",
  "encapsulation": "The binding of data (variables) and code (methods) together as a single unit (such as a class) while restricting direct external access, promoting data hiding and security.",
  "abstraction": "The process of hiding complex internal implementation details and displaying only the essential interfaces/features of an object to the user, typically implemented using abstract classes or pure virtual functions in C++.",
  "virtual function": "A member function in a base class that is declared with the 'virtual' keyword and overridden in a derived class. It ensures that the correct function is called for an object at runtime based on its actual type, achieving runtime polymorphism.",
  "constructor": "A special member function of a class that is automatically invoked when an object of that class is created. It has the same name as the class, no return type, and is used to initialize class variables. Types: Default, Parameterized, Copy.",
  "destructor": "A special member function of a class that is automatically invoked when an object goes out of scope or is deleted. It has the same name as the class prefixed with a tilde (~), no parameters, no return type, and is used to release resources.",
  "friend function": "A non-member function in C++ that is granted access to the private and protected members of a class. It is declared inside the class with the keyword 'friend'.",
  "inline function": "A performance optimization in C++ where the compiler replaces the function call with the actual function code, reducing the overhead of function calls for small, frequently used routines. Keyword: inline.",

  // === JAVA PROGRAMMING LANGUAGE ===
  "jvm": "Java Virtual Machine, the engine that drives the execution of Java bytecode. It provides a runtime environment, compiles bytecode into native machine code (JIT compiler), and performs automatic memory management (garbage collection).",
  "jdk": "Java Development Kit, a complete software development kit for Java. It contains the JRE, JVM, compiler (javac), documentation tools, and debugger tools required to write and compile Java applications.",
  "jre": "Java Runtime Environment, a package that provides the minimum libraries, JVM, and resources necessary to run an existing compiled Java application on a computer, without containing development tools like compilers.",
  "garbage collection": "An automatic memory management process in Java where the JVM detects and destroys objects that are no longer reachable or referenced by the program, reclaiming heap memory to prevent memory leaks.",
  "exception handling": "A robust mechanism in Java to handle runtime anomalies (like ArithmeticException, NullPointerException, or IOException) gracefully using try, catch, finally, throw, and throws blocks, preserving the normal execution flow.",
  "finally block": "A block in Java exception handling that is guaranteed to execute whether an exception is thrown or caught. It is typically used for clean-up tasks like closing database connections or files.",
  "interface": "A reference type in Java that is a collection of abstract methods and static constants. It specifies WHAT a class should do, but not HOW, enabling full multiple inheritance simulation. Keyword: interface.",
  "package": "A directory structure in Java used to group related classes, interfaces, and sub-packages together, avoiding naming conflicts and controlling access. Keyword: package.",
  "multithreading": "A Java feature that allows concurrent execution of two or more parts of a program (threads) to maximize CPU utilization. Threads can be created by extending the Thread class or implementing the Runnable interface.",
  "jdbc": "Java Database Connectivity, a standard Java API that defines how a Java application can connect to databases, send SQL statements, retrieve query results, and manage transactions.",

  // === DATA STRUCTURES & ALGORITHMS (DSA) ===
  "stack": "A linear, sequential data structure that follows the LIFO (Last In First Out) principle. Elements are inserted (push) and removed (pop) from a single end called the Top of the stack. Common operations: push(), pop(), peek(), isEmpty().",
  "queue": "A linear, sequential data structure that follows the FIFO (First In First Out) principle. Elements are inserted at the Rear end (enqueue) and removed from the Front end (dequeue). Types: Linear, Circular, Double-Ended (Deque), Priority Queue.",
  "linked list": "A dynamic, linear data structure comprising a sequence of nodes, where each node contains a data element and a pointer reference referencing the next node in the list. Types: Singly Linked List, Doubly Linked List, Circular Linked List.",
  "binary search tree": "A node-based binary tree data structure where each node has at most two children. The left subtree of a node contains only keys smaller than the node's key, and the right subtree contains keys larger, enabling quick O(log n) searches.",
  "bubble sort": "A simple, in-place sorting algorithm that repeatedly steps through a list, compares adjacent elements, and swaps them if they are in the incorrect order. This passes through the list until the entire sequence is sorted. Time complexity: O(n²).",
  "quick sort": "A highly efficient, divide-and-conquer sorting algorithm. It selects a 'pivot' element, partitions the array around the pivot such that smaller elements go left and larger go right, and then recursively sorts the sub-arrays. Average time complexity: O(n log n).",
  "binary search": "An efficient search algorithm that works on sorted arrays. It repeatedly divides the search interval in half: if the target is smaller than the middle element, it searches the left half; otherwise, it searches the right half. Time complexity: O(log n).",
  "linear search": "A simple search algorithm that checks every element in a list sequentially from the beginning to the end until a match is found. Works on both sorted and unsorted lists. Time complexity: O(n).",
  "tree traversal": "The process of visiting all nodes in a tree data structure exactly once. Types: Inorder (Left, Root, Right), Preorder (Root, Left, Right), Postorder (Left, Right, Root), and Level-order.",

  // === DATABASE MANAGEMENT & SQL ===
  "acid properties": "The foundational principles of reliable database transactions: Atomicity (all operations succeed or all fail), Consistency (database rules are preserved), Isolation (concurrent transactions don't interfere), and Durability (changes are permanent even during power loss).",
  "normalization": "A structured database design process that organizes tables to minimize data redundancy, duplication, and anomalies (Insert, Update, Delete) by dividing large tables into smaller, related tables and defining relations. Forms: 1NF, 2NF, 3NF, BCNF.",
  "sql join": "A query operation used to combine rows from two or more tables based on a related column between them. Types: INNER JOIN (matching rows), LEFT JOIN (all left + matching right), RIGHT JOIN (all right + matching left), FULL OUTER JOIN (all records).",
  "primary key": "A unique field or combination of fields in a database table that uniquely identifies each record. It cannot contain NULL values, must be unique, and there can only be one primary key per table.",
  "foreign key": "A database field in one table that references the primary key of another table. It establishes referential integrity and builds logical relationships between database tables.",
  "rdbms": "Relational Database Management System, a database system based on the relational model (tables of rows and columns) introduced by E.F. Codd. It enforces ACID properties and primary/foreign keys (e.g., MySQL, PostgreSQL, Oracle, SQL Server).",
  "nosql": "Not Only SQL, a non-relational database management system designed for storing unstructured or semi-structured data, offering high scalability and flexible schemas. Types: Document (MongoDB), Key-Value (Redis), Column-family (Cassandra), Graph (Neo4j).",
  "sql commands": "Structured Query Language commands divided into categories: DDL (Data Definition: CREATE, ALTER, DROP), DML (Data Manipulation: SELECT, INSERT, UPDATE, DELETE), DCL (Data Control: GRANT, REVOKE), and TCL (Transaction Control: COMMIT, ROLLBACK).",
  "trigger": "A stored database program that is automatically executed or fired in response to specific events (like INSERT, UPDATE, or DELETE statements) on a particular table, helping enforce custom business constraints.",
  "cursor": "A database object used by applications to point to, select, and process a set of rows returned by a SQL query one row at a time, serving as a row pointer during database operations.",

  // === OPERATING SYSTEMS & LINUX ===
  "operating system": "Core software that manages computer hardware resources, memory, processors, processes, and file systems, providing a platform and common services for application programs (e.g., Windows, macOS, Linux, Unix).",
  "linux commands": "Essential terminal commands for file and system management in Linux/Unix: 'ls' (list directory contents), 'cd' (change directory), 'mkdir' (make directory), 'rm' (remove file/folder), 'chmod' (change file permissions), 'grep' (pattern search).",
  "deadlock": "A state in operating systems where two or more processes are blocked permanently because each process holds a resource and waits for another resource held by another process in a circular chain. Conditions: Mutual Exclusion, Hold & Wait, No Preemption, Circular Wait.",
  "semaphore": "A non-negative integer variable used in operating systems for process synchronization and mutual exclusion, acting as a lock to coordinate concurrent processes and avoid race conditions. Functions: wait() (P) and signal() (V).",
  "paging": "A memory management scheme in operating systems where physical memory is divided into fixed-size blocks called 'frames', and logical memory is divided into blocks of the same size called 'pages', eliminating external fragmentation.",
  "segmentation": "A memory management scheme in operating systems that divides physical memory into logical segments of variable lengths based on program structures (like functions, arrays, stacks), aligning with the programmer's view of memory.",

  // === WEB TECHNOLOGIES ===
  "responsive design": "A web design methodology that utilizes CSS media queries, fluid grids, and flexible viewports to automatically adjust and scale layouts, ensuring web pages look beautiful on all screen sizes (mobile, tablet, desktop).",
  "javascript promise": "An object representing the eventual completion or failure of an asynchronous operation in JavaScript. It can be in one of three states: Pending, Fulfilled, or Rejected, facilitating clean asynchronous coding using .then() and .catch().",
  "react component": "The building block of a React application's UI. It is an independent, reusable piece of code (functional or class-based) that accepts parameters called 'props' and returns JSX markup describing the interface.",
  "rest api": "Representational State Transfer API, a stateless web service architecture that allows systems to communicate over HTTP using standard methods: GET (read), POST (create), PUT (update), and DELETE (remove).",

  // === BRABU BCA ACADEMIC FAQs ===
  "passing marks details": "To pass a paper in BRABU BCA, a student must secure at least 45% marks in theory papers (written university exam + internals combined) and 45% marks in practical laboratory exams separately. Scoring below this in any paper results in a carry-over status.",
  "exam prep guide": "To score outstanding marks: 1. Deeply study the solved Previous Year Questions (PYQs) for the last 5 years in the Subjects page. 2. Attempt quizzes in the Test Hub to build MCQ confidence. 3. Practice mock C, C++, Java programs. 4. Focus on attempting exactly 5 long questions in the exam.",
  "project report format": "In Semester 6, students must submit a comprehensive Project Report (BCA-601, 100 Marks) documenting a fully functional web or software application, accompanied by a Seminar presentation (BCA-602, 50 Marks) and an oral Viva-Voce (BCA-603, 50 Marks)."
};

// Merge with any existing knowledge
if (typeof BCA_BOT_KNOWLEDGE !== 'undefined') {
  Object.assign(BCA_BOT_KNOWLEDGE, COMPUTER_FUNDAMENTALS_KNOWLEDGE);
}
